---
# Configure flask-dummy to setup nginx virtualhost,
# pull the repository then restart nginx

- name: ensure webapp path
  file: path={{ source_path }} state=directory owner=root group=root recurse=yes
  tags: [configuration,flask-dummy]

- name: pull the branch master to the latest commit
  git: repo={{ repo}} 
       dest={{ source_path }}
       version={{ branch }}
  tags: [configuration,git,flask-dummy]

- name: create supervisord config folder
  action: file dest=/etc/supervisor state=directory owner=root

- name: create supervisord config
  action: template src=supervisord.conf dest=/etc/supervisord.conf
  tags: [configuration,supervisord]

- name: create supervisord init script
  action: template src=supervisord.sh dest=/etc/init.d/supervisord mode=0755
  tags: [configuration,supervisord]

- name: start supervisord service and have it run during system startup
  action: service name=supervisord state=started enabled=yes
  tags: [configuration,supervisord]

- name: create supervisor program config
  action: template src=supervisor.ini dest="/etc/supervisor/{{ app_name }}.ini"
  notify:
    - restart flask-dummy

- name: start app
  action: supervisorctl name=${app_name} state=started

- name: add the nginx virtualhost
  copy: src={{ nginx_virtualhost }} dest=/etc/nginx/sites-available/
  tags: [configuration,nginx,flask-dummy]

- name: Create links for sites-enabled
  file: state=link 
        src="/etc/nginx/sites-available/{{ nginx_virtualhost }}"
        dest="/etc/nginx/sites-enabled/{{ nginx_virtualhost }}"
  notify:
   - reload nginx
  tags: [configuration,nginx,flask-dummy]

- name: Disable the default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
  - reload nginx
  tags: [configuration,nginx,flask-dummy]

- name: Remove the default configuration
  file: path=/etc/nginx/conf.d/default.conf state=absent
  notify:
  - reload nginx
  tags: [configuration,nginx,flask-dummy]
